framework:
    asset_mapper:
        # The paths to make available to the asset mapper.
        paths:
            - assets/
        excluded_patterns:
            - '*/.*'
            - node_modules
        server: false

        # Optional but recommended - public paths will be handled by Symfony
        public_prefix: /assets

when@prod:
    framework:
        asset_mapper:
            missing_import_mode: warn
